# Mosquitto broker — Équateur
# Topic : futurekawa/equateur/{entrepot}/sensors

listener 1883
allow_anonymous true

persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data/

log_type all
log_dest stdout

max_inflight_messages 20
