version: "3.9"

services:
  mosquitto-bresil:
    image: eclipse-mosquitto:2
    container_name: mosquitto-bresil
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      - bresil-net

  mysql-bresil:
    image: mysql:8.0
    container_name: mysql-bresil
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-bresil-data:/var/lib/mysql
    networks:
      - bresil-net

  api-bresil:
    build: ./api
    container_name: api-bresil
    env_file: .env
    ports:
      - "8001:8000"
    depends_on:
      - mysql-bresil
      - mosquitto-bresil
    networks:
      - bresil-net

  node-red-bresil:
    image: nodered/node-red:latest
    container_name: node-red-bresil
    volumes:
      - ./node-red/flows.json:/data/flows.json
    ports:
      - "1880:1880"
    depends_on:
      - mosquitto-bresil
    networks:
      - bresil-net

volumes:
  mysql-bresil-data:

networks:
  bresil-net:
    driver: bridge
