sonar.projectKey=futurekawa
sonar.projectName=FutureKawa IoT
sonar.projectVersion=1.0

sonar.sources=pays,siege,iot
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,**/test/**,iot/firmware/**

sonar.python.version=3.13
sonar.python.coverage.reportPaths=tests/reports/coverage.xml
sonar.python.pylint.reportPaths=tests/reports/pylint-report.txt
sonar.junit.reportPaths=tests/reports/unit-results.xml,tests/reports/integration-results.xml,tests/reports/newman-results.xml
sonar.javascript.lcov.reportPaths=tests/reports/lcov.info

sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=external_pylint:E0401
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
sonar.issue.ignore.multicriteria.e2.ruleKey=external_pylint:R0801
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*
sonar.issue.ignore.multicriteria.e3.ruleKey=javascript:S6774
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*

sonar.qualitygate.wait=true
