sonar.projectKey=futurekawa
sonar.projectName=FutureKawa IoT
sonar.projectVersion=1.0

sonar.sources=pays,siege,iot
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,**/test/**

sonar.python.coverage.reportPaths=tests/reports/coverage.xml
sonar.python.pylint.reportPaths=tests/reports/pylint-report.txt
sonar.junit.reportPaths=tests/reports/unit-results.xml,tests/reports/integration-results.xml,tests/reports/newman-results.xml
sonar.javascript.lcov.reportPaths=tests/reports/lcov.info

sonar.qualitygate.wait=true
